### ISSUE TITLE
UnFUG Design

### ISSUE THREAD

**Issue by violentinternet** [TheNeikos/HFU-Presentations-Vorlage#2]
It would be cool to have LaTeX template for UnFUG. It could use some light blue colors like used for UnFUCK-Logo.

**Comment by violentinternet** [comment]
It would be also OK to just exchange the colors and the logo.

**Comment by TheNeikos** [comment]
Sounds good, gonna take a look at it.

**Comment by TheNeikos** [comment]
It has been added
