### ISSUE TITLE
Make fails because of xvdipdfmx

### ISSUE THREAD

**Issue by matthiasbeyer** [TheNeikos/HFU-Presentations-Vorlage#6]
After some latex warning output:

```
LaTeX Font Warning: Font shape `EU1/arialn.ttf(0)/m/it' undefined
(Font)              using `EU1/arialn.ttf(0)/m/n' instead on input line 103.

<hfu_unfug.eps>
Overfull \vbox (9.0pt too high) has occurred while \output is active [4]
<hfu_unfug.eps>
Overfull \vbox (9.0pt too high) has occurred while \output is active [5/usr/bin/env: „texlua“: No such file or directory

xdvipdfmx:fatal: pdf_ref_obj(): passed invalid object.

Output file removed.

pandoc: Error producing PDF
```

Not sure whether pandoc is the issue or something else, though.

**Comment by matthiasbeyer** [comment]
Could also be an packaging error, actually.

**Comment by TheNeikos** [comment]
Do you have texlua installed?

**Comment by matthiasbeyer** [comment]
Nope, [unfortunately not](https://github.com/NixOS/nixpkgs/issues/19301).

**Comment by TheNeikos** [comment]
This seems to be the cause of the error then, I am not sure why that is requried though

**Comment by matthiasbeyer** [comment]
Me too, and I'm also confused by the fact that packaging should have noticed that `luatex` is a dependecy, and if it really is, that it is broken in our packaging.

I'm closing this now, as your code seems not to be the issue.
